Superheroes/Controllers/SuperheroController.cs
using Superheroes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Superheroes.Controllers
{
    public class SuperheroController : Controller
    {
        SuperheroRepository superheroRepository = new SuperheroRepository();

        // GET: Superhero
        public ActionResult Index()
        {
            var superheroes = superheroRepository.FindAllSuperheroes().ToList();

            return View("Index", superheroes);
        }

        [HttpPost]
        public ActionResult Create(Superhero superhero)
        {
            superheroRepository.Add(superhero);
            superheroRepository.Save();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Read()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            Superhero superhero = superheroRepository.GetSuperhero(id);

            if (superhero == null)
                return View("NotFound");
            else
                return View("Details", superhero);
        }

        public ActionResult Update(int id)
        {
            Superhero superhero = superheroRepository.GetSuperhero(id);

            if (superhero == null)
            {
                return View("NotFound");
            }
            else
            {
                UpdateModel(superhero);

                superheroRepository.Save();

                var superheroes = superheroRepository.FindAllSuperheroes();
                return View(superhero);
                //return RedirectToAction("Index");
            }
        }
        
        public ActionResult Delete(int id)
        {
            Superhero superhero = superheroRepository.GetSuperhero(id);

            if (superhero == null)
            {
                return View("NotFound");
            }
            else
            {
                superheroRepository.Delete(superhero);

                superheroRepository.Save();

                var superheroes = superheroRepository.FindAllSuperheroes();
                return View("Index", superheroes);
            }
        }
        
    }
}

Superheroes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Superhero Database</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Superheroes", "Index", "Superhero", new { area = "" }, new { @class = "navbar-brand" })
            </div>
       </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>